shared:
  image: node:12
  steps:
    - echo: echo hi
jobs:
  main:
    requires: [~commit, ~pr]
  internal_fork:
    requires: [main]
  join_job:
    requires: [internal_fork, sd@7411:external_fork, sd@7410:external_fork]
  join_job1:
    requires: [internal_fork, sd@7411:external_fork]
  no_join:
    requires: [internal_fork]
